export const WALLET_BSC_CONNECTED = 'WALLET_BSC_CONNECTED'
export const WALLET_BSC_DISCONNECTED = 'WALLET_BSC_DISCONNECTED'
export const WALLET_BSC_NETWORK_CHANGED = 'WALLET_BSC_CONNECTED'
export const WALLET_BSC_ACCOUNT_CHANGED = 'WALLET_BSC_CONNECTED'